import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

export default function Layout({ children }) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<header>
				<Link href={'/'}>
					<a>Home</a>
				</Link>
				<Link href={'/about'}>
					<a>About</a>
				</Link>
			</header>

			<main className='main'>{children}</main>

			<footer className='footer'>
				<a
					href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
					target='_blank'
					rel='noopener noreferrer'>
					Powered by{' '}
					<span className='image'>
						<Image
							src='/vercel.svg'
							alt='Vercel Logo'
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</>
	);
}
